# Generated by Django 4.0.1 on 2022-02-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='TaskHistory',
        ),
    ]
